function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{typeof(detect_bedgraph),IOStream})
    precompile(Tuple{typeof(detect_noometiff),IOStream})
    precompile(Tuple{typeof(detect_rdata),IOStream})
    precompile(Tuple{typeof(detect_rdata_single),IOStream})
    precompile(Tuple{typeof(detectwav),IOStream})
    precompile(Tuple{typeof(load),File})
    precompile(Tuple{typeof(load),String})

    precompile(Tuple{typeof(query),String})
    precompile(Tuple{typeof(query),IOStream})
    precompile(Tuple{typeof(query),IOStream,String})
    precompile(Tuple{typeof(hasfunction),Function})
    precompile(Tuple{typeof(hasmagic),Function})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{10,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{20,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{30,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{32,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{35,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{4,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{6,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{7,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},NTuple{8,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},Tuple{UInt8,UInt8,UInt8}})
    precompile(Tuple{typeof(iter_eq),Array{UInt8,1},Tuple{UInt8,UInt8}})
end
